/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package prj11.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 04-28-2010
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** password property */
	private String password;

	/** account property */
	private String account;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if(account.length()==0){ 
			ActionMessage error = new ActionMessage("error.null","account"); 
			errors.add("account",error);			
		}
		else if(account.length()>10 || account.length()<6 ){ 
			ActionMessage error = new ActionMessage("error.length","account","6","10");
			errors.add("account",error);	
		}
		if(password.length()==0){ 
			ActionMessage error = new ActionMessage("error.null","password"); 
			errors.add("password",error);		
		}
		else if(password.length()>10 || password.length()<6 ){ 
			ActionMessage error = 
	new ActionMessage("error.length","password","6","10");
			errors.add("password",error);	
		}
		return errors;

	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the account.
	 * @return String
	 */
	public String getAccount() {
		return account;
	}

	/** 
	 * Set the account.
	 * @param account The account to set
	 */
	public void setAccount(String account) {
		this.account = account;
	}
}